/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
public interface ParserConstants {

  int EOF = 0;
  int SEMI = 1;
  int ASGN = 2;
  int PRINT = 3;
  int LPAR = 4;
  int RPAR = 5;
  int PLUS = 6;
  int MINUS = 7;
  int TIMES = 8;
  int DIVIDE = 9;
  int MOD = 10;
  int POWER = 11;
  int DIGIT = 12;
  int ID = 13;
  int NUM = 14;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\";\"",
    "\"=\"",
    "\"print\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "<DIGIT>",
    "<ID>",
    "<NUM>",
    "<token of kind 15>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
